dbt_duckdb_sample:
  outputs:
    dev:
      type: duckdb
      path: /storage/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: /storage/prod.duckdb
      threads: 4
  target: dev
